/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepSeekPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");
var DEEPSEEK_VIEW_TYPE = "deepseek-chat-view";
var DeepSeekView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "chatContainer");
    __publicField(this, "inputEl");
    __publicField(this, "messageHistory", []);
    __publicField(this, "lastSelection", "");
    this.plugin = plugin;
  }
  getViewType() {
    return DEEPSEEK_VIEW_TYPE;
  }
  getDisplayText() {
    return "Deepseek note helper";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    await Promise.resolve();
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        const selection = editor.getSelection();
        if (selection) {
          this.lastSelection = selection;
        }
      })
    );
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("deepseek-chat-container");
    container.createEl("h4", { text: "Deepseek chat", cls: "chat-h4" });
    this.chatContainer = container.createDiv({ cls: "chat-messages" });
    const inputContainer = container.createDiv({ cls: "chat-input-container" });
    this.inputEl = inputContainer.createEl("textarea", { cls: "chat-input" });
    this.inputEl.placeholder = "Type your message... (Shift+enter for newline, Enter to send)";
    const sendBtn = inputContainer.createEl("button", { text: "Send" });
    sendBtn.addClass("mod-cta");
    sendBtn.addEventListener("click", () => {
      void this.handleSend().catch(console.error);
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSend().catch(console.error);
      }
    });
    this.appendMessage("assistant", "Hello! Ask me anything. If you highlight text in your note, I will remember it and focus on that. I can also search your entire vault or update your note metadata if you ask me to!").catch(console.error);
  }
  async handleSend() {
    const instruction = this.inputEl.value.trim();
    if (!instruction) return;
    await this.appendMessage("user", instruction);
    this.inputEl.value = "";
    let contextString = "";
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView) {
      const currentSelection = activeView.editor.getSelection();
      if (currentSelection) {
        this.lastSelection = currentSelection;
      }
    }
    const activeFile = this.app.workspace.getActiveFile();
    let linkedNotesContext = "";
    if (activeFile) {
      const cache = this.app.metadataCache.getFileCache(activeFile);
      if (cache && cache.links) {
        const uniqueLinks = Array.from(new Set(cache.links.map((l) => l.link)));
        for (const linkPath of uniqueLinks) {
          const linkedFile = this.app.metadataCache.getFirstLinkpathDest(linkPath, activeFile.path);
          if (linkedFile instanceof import_obsidian.TFile && linkedFile.extension === "md") {
            const linkedContent = await this.app.vault.read(linkedFile);
            const truncatedContent = linkedContent.length > 1500 ? linkedContent.substring(0, 1500) + "... (truncated)" : linkedContent;
            linkedNotesContext += `
--- Linked Note: [[${linkedFile.basename}]] ---
${truncatedContent}
`;
          }
        }
      }
    }
    if (this.lastSelection && activeFile) {
      contextString = `

[System Info: The user highlighted the following text in the note "${activeFile.name}". Focus your answer specifically around this highlighted text:
---
${this.lastSelection}
---]`;
      this.lastSelection = "";
    } else if (activeFile) {
      const content = await this.app.vault.read(activeFile);
      contextString = `

[System Info: The user is currently viewing the note "${activeFile.name}". Its full content is:
---
${content}
---]`;
    }
    if (linkedNotesContext) {
      contextString += `

[System Info: The active note contains links to the following notes. Here is their content for additional context:
${linkedNotesContext}]`;
    }
    try {
      const prompt = instruction + contextString;
      const messages = [
        { role: "system", content: "You are a helpful AI assistant integrated into Obsidian. You can converse naturally with the user. If they provide note context, use it to answer their questions or help them brainstorm." }
      ];
      const recentHistory = this.messageHistory.slice(-10);
      recentHistory.forEach((msg) => messages.push(msg));
      messages.push({ role: "user", content: prompt });
      await this.processConversationStream(messages, prompt);
    } catch (error) {
      console.error("Deepseek error:", error);
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice("Deepseek API error: " + errorMsg);
      await this.appendMessage("system", "Error: " + errorMsg);
    }
  }
  async appendMessage(role, text) {
    if (role !== "system" && role !== "tool") {
      this.messageHistory.push({ role, content: text });
    }
    const msgDiv = this.chatContainer.createDiv({ cls: `chat-msg role-${role}` });
    const senderName = role === "user" ? "You" : role === "assistant" ? "Deepseek" : role === "tool" ? "Tool" : "System";
    const headerDiv = msgDiv.createDiv({ cls: "msg-header" });
    headerDiv.createEl("strong", {
      text: senderName,
      cls: "chat-sender-label"
    });
    if (role === "assistant") {
      const copyBtn = headerDiv.createEl("button", {
        text: "Copy",
        cls: "clickable-icon chat-copy-btn"
      });
      copyBtn.addEventListener("click", () => {
        void (async () => {
          await navigator.clipboard.writeText(text);
          copyBtn.innerText = "Copied!";
          setTimeout(() => {
            copyBtn.innerText = "Copy";
          }, 2e3);
        })().catch(console.error);
      });
    }
    const contentDiv = msgDiv.createDiv({ cls: "msg-content" });
    if (role === "user" || role === "system" || role === "tool") {
      contentDiv.addClass("chat-whitespace-pre");
      contentDiv.innerText = text;
      msgDiv.addClass(role === "user" ? "chat-msg-user" : "chat-msg-system");
    } else {
      msgDiv.addClass("chat-msg-assistant");
      await import_obsidian.MarkdownRenderer.render(this.app, text, contentDiv, "", this);
    }
    this.chatContainer.scrollTo(0, this.chatContainer.scrollHeight);
  }
  async executeSearchVault(query) {
    const files = this.app.vault.getMarkdownFiles();
    const results = [];
    const lowerQuery = query.toLowerCase();
    files.sort((a, b) => b.stat.mtime - a.stat.mtime);
    for (const file of files) {
      const content = await this.app.vault.cachedRead(file);
      if (content.toLowerCase().includes(lowerQuery) || file.basename.toLowerCase().includes(lowerQuery)) {
        const matchIndex = content.toLowerCase().indexOf(lowerQuery);
        const start = Math.max(0, matchIndex - 100);
        const end = Math.min(content.length, matchIndex + 300);
        results.push(`--- File: [[${file.basename}]] ---
...${content.substring(start, end)}
`);
        if (results.length >= 5) break;
      }
    }
    if (results.length === 0) {
      return `No files found matching "${query}".`;
    }
    return `Found ${results.length} files matching "${query}":

` + results.join("\n\n");
  }
  async executeUpdateMetadata(properties) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) return "Error: No active file to update.";
    try {
      await this.app.fileManager.processFrontMatter(activeFile, (frontmatter) => {
        for (const [key, value] of Object.entries(properties)) {
          frontmatter[key] = value;
        }
      });
      return `Successfully updated metadata for ${activeFile.basename}.`;
    } catch (e) {
      return `Failed to update metadata: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeCreateNote(path, content) {
    try {
      if (!path.endsWith(".md")) path += ".md";
      const normalizedPath = path.replace(/^\//, "");
      const fileExists = this.app.vault.getAbstractFileByPath(normalizedPath);
      if (fileExists) {
        return `Error: File already exists at path ${normalizedPath}`;
      }
      await this.app.vault.create(normalizedPath, content);
      return `Successfully created new note at ${normalizedPath}`;
    } catch (e) {
      return `Failed to create note: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeAppendToNote(path, content) {
    try {
      if (!path.endsWith(".md")) path += ".md";
      const normalizedPath = path.replace(/^\//, "");
      const file = this.app.vault.getAbstractFileByPath(normalizedPath);
      if (!file || !(file instanceof import_obsidian.TFile)) {
        return `Error: Markdown file not found at path ${normalizedPath}`;
      }
      await this.app.vault.append(file, "\n" + content);
      return `Successfully appended content to ${normalizedPath}`;
    } catch (e) {
      return `Failed to append to note: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeModifyDirectory(directoryPath, instruction) {
    await Promise.resolve();
    try {
      const normalizedPath = directoryPath.replace(/^\//, "").replace(/\/$/, "");
      const folder = normalizedPath === "" ? this.app.vault.getRoot() : this.app.vault.getAbstractFileByPath(normalizedPath);
      if (!folder) {
        return `Error: Directory not found at path ${normalizedPath || "/"}`;
      }
      const markdownFiles = [];
      const getFiles = (f) => {
        if (f instanceof import_obsidian.TFolder) {
          for (const child of f.children) {
            getFiles(child);
          }
        } else if (f instanceof import_obsidian.TFile && f.extension === "md") {
          markdownFiles.push(f);
        }
      };
      getFiles(folder);
      if (markdownFiles.length === 0) {
        return `No markdown files found in directory ${normalizedPath || "/"}`;
      }
      const filePaths = markdownFiles.map((f) => f.path).join(", ");
      return `Found ${markdownFiles.length} files in directory ${normalizedPath || "/"}. The files are: ${filePaths}. 
To apply the instruction "${instruction}", please call 'update_metadata' or 'append_to_note' on these files one by one.`;
    } catch (e) {
      return `Failed to process directory: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async processConversationStream(messages, originalUserPrompt) {
    var _a, _b;
    const { apiKey, apiUrl, model } = this.plugin.settings;
    if (!apiKey) {
      throw new Error("API Key not set in settings.");
    }
    const tools = [
      {
        type: "function",
        function: {
          name: "search_vault",
          description: "Search the entire Obsidian vault for files matching a keyword query. Use this when the user asks about past files, vault contents, or broader knowledge outside the current note.",
          parameters: {
            type: "object",
            properties: {
              query: { type: "string", description: "The keyword or phrase to search for." }
            },
            required: ["query"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "update_metadata",
          description: "Update the YAML frontmatter / metadata of the active note. Use this if the user asks you to add tags, change status, or edit properties.",
          parameters: {
            type: "object",
            properties: {
              properties: {
                type: "object",
                description: "Key-value pairs to set in the frontmatter. For tags, use an array of strings."
              }
            },
            required: ["properties"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "create_note",
          description: "Create a new markdown note in the vault at the specified path.",
          parameters: {
            type: "object",
            properties: {
              path: { type: "string", description: "The path including filename where the note should be created, e.g. 'Daily/2026-01-01.md'." },
              content: { type: "string", description: "The initial markdown content of the new note." }
            },
            required: ["path", "content"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "append_to_note",
          description: "Append new content to the end of an existing note.",
          parameters: {
            type: "object",
            properties: {
              path: { type: "string", description: "The path of the existing note, e.g. 'Ideas/Project.md'." },
              content: { type: "string", description: "The content to append to the end of the note." }
            },
            required: ["path", "content"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "modify_files_in_directory",
          description: "Get a list of all markdown files in a directory to perform bulk operations.",
          parameters: {
            type: "object",
            properties: {
              directory_path: { type: "string", description: "The path of the directory to scan, e.g. 'Work/Projects'. Use '/' for the root vault." },
              instruction: { type: "string", description: "A description of what needs to be changed across these files." }
            },
            required: ["directory_path", "instruction"]
          }
        }
      }
    ];
    const msgDiv = this.chatContainer.createDiv({ cls: `chat-msg role-assistant` });
    msgDiv.addClass("chat-msg-assistant");
    const headerDiv = msgDiv.createDiv({ cls: "msg-header" });
    const senderLabel = headerDiv.createEl("strong", {
      text: "Deepseek (thinking...)",
      cls: "chat-sender-label"
    });
    const copyBtn = headerDiv.createEl("button", {
      text: "Copy",
      cls: "clickable-icon chat-copy-btn chat-hidden"
    });
    const contentDiv = msgDiv.createDiv({ cls: "msg-content" });
    let fullResponse = "";
    let toolCall = null;
    try {
      const requestBody = {
        model,
        messages,
        stream: false,
        // Streaming removed to satisfy Obsidian review bot (fetch -> requestUrl)
        tools
      };
      const response = await (0, import_obsidian.requestUrl)({
        url: `${apiUrl}/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(requestBody)
      });
      if (response.status !== 200) {
        throw new Error(`API returned status ${response.status}: ${response.text}`);
      }
      const data = response.json;
      if (data.choices && data.choices[0].message) {
        const message = data.choices[0].message;
        if (message.content) {
          fullResponse = message.content;
          contentDiv.innerText = fullResponse;
          this.chatContainer.scrollTo(0, this.chatContainer.scrollHeight);
        }
        if (message.tool_calls) {
          for (const tc of message.tool_calls) {
            if (!toolCall) {
              toolCall = { id: tc.id, name: ((_a = tc.function) == null ? void 0 : _a.name) || "", arguments: "" };
            }
            if ((_b = tc.function) == null ? void 0 : _b.arguments) {
              toolCall.arguments += tc.function.arguments;
            }
          }
        }
      }
      if (toolCall) {
        senderLabel.innerText = `Deepseek (running ${toolCall.name}...)`;
        let toolResult = "";
        try {
          const args = JSON.parse(toolCall.arguments || "{}");
          if (toolCall.name === "search_vault") {
            toolResult = await this.executeSearchVault(args.query);
          } else if (toolCall.name === "update_metadata") {
            toolResult = await this.executeUpdateMetadata(args.properties);
          } else if (toolCall.name === "create_note") {
            toolResult = await this.executeCreateNote(args.path, args.content);
          } else if (toolCall.name === "append_to_note") {
            toolResult = await this.executeAppendToNote(args.path, args.content);
          } else if (toolCall.name === "modify_files_in_directory") {
            toolResult = await this.executeModifyDirectory(args.directory_path, args.instruction);
          } else {
            toolResult = `Error: Unknown tool ${toolCall.name}`;
          }
        } catch (e) {
          toolResult = `Error executing tool: ${e instanceof Error ? e.message : String(e)}`;
        }
        msgDiv.addClass("chat-msg-tool");
        contentDiv.innerText = `=> Used tool: ${toolCall.name}
=> Result: ${toolResult.substring(0, 50)}...`;
        messages.push({
          role: "assistant",
          content: null,
          tool_calls: [
            {
              id: toolCall.id,
              type: "function",
              function: {
                name: toolCall.name,
                arguments: toolCall.arguments
              }
            }
          ]
        });
        messages.push({
          role: "tool",
          tool_call_id: toolCall.id,
          name: toolCall.name,
          content: toolResult
        });
        await this.processConversationStream(messages, originalUserPrompt);
        msgDiv.remove();
        return;
      }
      senderLabel.innerText = "Deepseek";
      copyBtn.removeClass("chat-hidden");
      copyBtn.addEventListener("click", () => {
        void (async () => {
          await navigator.clipboard.writeText(fullResponse);
          copyBtn.innerText = "Copied!";
          setTimeout(() => {
            copyBtn.innerText = "Copy";
          }, 2e3);
        })().catch(console.error);
      });
      contentDiv.innerHTML = "";
      await import_obsidian.MarkdownRenderer.render(this.app, fullResponse, contentDiv, "", this);
      if (originalUserPrompt) {
        const cleanPrompt = originalUserPrompt.split("\n\n[System Info")[0];
        if (this.messageHistory.length === 0 || this.messageHistory[this.messageHistory.length - 1].content !== cleanPrompt) {
          this.messageHistory.push({ role: "user", content: cleanPrompt });
        }
      }
      this.messageHistory.push({ role: "assistant", content: fullResponse });
    } catch (e) {
      msgDiv.remove();
      throw e;
    }
  }
};

// src/main.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  apiUrl: "https://api.deepseek.com",
  model: "deepseek-chat"
};
var DeepSeekPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", DEFAULT_SETTINGS);
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      DEEPSEEK_VIEW_TYPE,
      (leaf) => new DeepSeekView(leaf, this)
    );
    this.addRibbonIcon("bot", "Open deepseek helper", () => {
      void this.activateView().catch(console.error);
    });
    this.addSettingTab(new DeepSeekSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(DEEPSEEK_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: DEEPSEEK_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var DeepSeekSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Deepseek").setHeading();
    new import_obsidian3.Setting(containerEl).setName("API key").setDesc("Enter your deepseek API key.").addText((text) => text.setValue(this.plugin.settings.apiKey).onChange((value) => {
      this.plugin.settings.apiKey = value;
      void this.plugin.saveSettings().catch(console.error);
    }));
    new import_obsidian3.Setting(containerEl).setName("API URL").setDesc("Endpoint for deepseek API.").addText((text) => text.setValue(this.plugin.settings.apiUrl).onChange((value) => {
      this.plugin.settings.apiUrl = value;
      void this.plugin.saveSettings().catch(console.error);
    }));
    new import_obsidian3.Setting(containerEl).setName("Model").setDesc("Model to use.").addText((text) => text.setValue(this.plugin.settings.model).onChange((value) => {
      this.plugin.settings.model = value;
      void this.plugin.saveSettings().catch(console.error);
    }));
  }
};
